# Generated by Django 3.2.5 on 2022-02-24 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creations',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creations',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updators', to=settings.AUTH_USER_MODEL),
        ),
    ]
