# Generated by Django 3.2.5 on 2022-02-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0003_auto_20220225_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creations',
            name='up_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creations',
            name='up_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
