# Generated by Django 3.2.5 on 2022-03-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0004_auto_20220225_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creations',
            name='up_area',
        ),
        migrations.RemoveField(
            model_name='creations',
            name='up_hei',
        ),
        migrations.RemoveField(
            model_name='creations',
            name='up_len',
        ),
        migrations.RemoveField(
            model_name='creations',
            name='up_vol',
        ),
        migrations.RemoveField(
            model_name='creations',
            name='up_wid',
        ),
        migrations.RemoveField(
            model_name='creations',
            name='updator',
        ),
    ]
